"""Custom vehicles for user missions (War Thunder CDK "userVehicles" mechanism).

A user mission can use `unit_class:t="userVehicles/<host>"`: the game loads
content/pkg_local/gameData/<units folder>/userVehicles/<host>.blk. We write that file as
`include` of the real vehicle + `@override:` lines for the user's modifications.
<host> is a reserve vehicle every account owns (US reserves by default).

Safety rules:
  * only NEW paths are written (userVehicles/, weapons/wtftd/, fm/wtftd_*, weaponPresets/wtftd_*),
    never a path that shadows a real game file, so online battles are not affected;
  * every written file is listed in user/cdk_manifest.json and can be removed with cleanup();
  * an existing host file that WTFTD did not write is backed up before being replaced.
"""
from __future__ import annotations

import json
import re
import shutil
import time
from pathlib import Path

MARKER = "// generated by WTFTD"
SAFE = re.compile(r"^[A-Za-z0-9_\-.]{1,120}$")
INCLUDE_ROOT = "#/develop/gameBase/"

DEFAULT_HOSTS = {
    "ground": "us_m2a4",
    "air": "p-26a_34_m2",
    "heli": "",
    "boat": "us_pt6",
    "ship": "us_destroyer_clemson_litchfield",
}
UNIT_DIRS = {
    "ground": "gameData/units/tankModels",
    "air": "gameData/flightModels",
    "heli": "gameData/flightModels",
    "boat": "gameData/units/ships",
    "ship": "gameData/units/ships",
}
CUSTOM_PRESET = "wtftd_custom"
# How aircraft / helicopters are loaded:
#   "custom"       - new aircraft file content/pkg_user/gameData/flightModels/wtftd_<id>.blk (CDK docs);
#                    the ownership check only applies to shop vehicles.
#   "userVehicles" - same as ground vehicles (tested: the game loads the real host aircraft instead).
AIR_METHODS = ("custom", "userVehicles")
PACKAGES = ("pkg_local", "pkg_user")


class CdkError(Exception):
    pass


def _r(v) -> str:
    v = float(v)
    s = repr(round(v, 6))
    return s[:-2] if s.endswith(".0") else s


def _num(d: dict, key: str, lo: float, hi: float):
    v = d.get(key)
    if v in (None, ""):
        return None
    try:
        v = float(v)
    except (TypeError, ValueError):
        raise CdkError(f"Invalid value for {key}")
    if not lo <= v <= hi:
        raise CdkError(f"{key} must be between {lo} and {hi}")
    return v


def _blk_value(typ: str, v) -> str:
    if typ == "r":
        return _r(v)
    if typ == "i":
        return str(int(v))
    if typ == "b":
        return "yes" if v else "no"
    if typ == "t":
        return f'"{v}"'
    if typ in ("p2", "p3", "p4"):
        return ", ".join(_r(x) for x in v)
    raise CdkError(f"Unknown value type {typ}")


class Blk:
    """Tiny writer for override files."""

    def __init__(self):
        self.lines: list[str] = []
        self.ind = 0

    def line(self, s: str):
        self.lines.append("  " * self.ind + s)

    def open(self, name: str):
        self.line(f'"@override:{name}"{{')
        self.ind += 1

    def close(self):
        self.ind -= 1
        self.line("}")

    def real(self, name: str, v):
        self.line(f'"@override:{name}":r={_r(v)}')

    def int(self, name: str, v):
        self.line(f'"@override:{name}":i={int(v)}')

    def p2(self, name: str, v):
        self.line(f'"@override:{name}":p2={_r(v[0])}, {_r(v[1])}')

    def p3(self, name: str, v):
        self.line(f'"@override:{name}":p3={_r(v[0])}, {_r(v[1])}, {_r(v[2])}')

    def text(self, name: str, v: str):
        self.line(f'"@override:{name}":t="{v}"')

    def __str__(self):
        return "\n".join(self.lines) + "\n"


def _header(what: str, include: str) -> Blk:
    b = Blk()
    b.line(f"{MARKER} - {what} - {time.strftime('%Y-%m-%d %H:%M')}")
    b.line(f'include "{INCLUDE_ROOT}{include}"')
    b.line("")
    return b


def _shell_block(b: Blk, sm: dict):
    """Writes overrides for one bullet block from {v, m, e, h, l}."""
    b.open("bullet")
    if sm.get("v") is not None:
        b.real("speed", sm["v"])
    if sm.get("m") is not None:
        b.real("mass", sm["m"])
    if sm.get("e") is not None:
        b.real("explosiveMass", sm["e"])
    if sm.get("h") is not None:
        b.open("cumulativeDamage")
        b.real("armorPower", sm["h"])
        b.close()
    if sm.get("l") is not None:
        b.open("damage")
        b.open("kinetic")
        b.real("lanzOdermattWorkingLength", sm["l"])
        b.close()
        b.close()
    b.close()


def _clean_shells(shells: dict, group: dict) -> dict:
    """Validates {set_id: {v,m,e,h,l}} against the gun's known ammo sets."""
    known = {o["id"]: o.get("s", {}) for o in group.get("opts", [])}
    out = {}
    for sid, vals in (shells or {}).items():
        if sid not in known or not isinstance(vals, dict):
            continue
        base = known[sid]
        sm = {}
        for k, lo, hi in (("v", 1, 20000), ("m", 0.001, 10000), ("e", 0, 10000), ("h", 0, 100000), ("l", 1, 100000)):
            if k in base:
                v = _num(vals, k, lo, hi)
                if v is not None and abs(v - base[k]) > 1e-9:
                    sm[k] = v
        if sm:
            out[sid] = sm
    return out


def _weapon_slots(unit_data: dict | None) -> dict[int, tuple[int, str]]:
    """Slot index -> (1-based position of its WeaponSlot block, bomb emitter of that slot or "")."""
    ws = (unit_data or {}).get("WeaponSlots")
    sl = ws.get("WeaponSlot") if isinstance(ws, dict) else None
    sl = sl if isinstance(sl, list) else [sl] if isinstance(sl, dict) else []
    out = {}
    for pos, s in enumerate(sl, start=1):
        if not isinstance(s, dict) or not isinstance(s.get("index"), int):
            continue
        bomb_em = ""
        wps = s.get("WeaponPreset")
        for wp in wps if isinstance(wps, list) else [wps] if isinstance(wps, dict) else []:
            ws_ = wp.get("Weapon") if isinstance(wp, dict) else None
            for w in ws_ if isinstance(ws_, list) else [ws_] if isinstance(ws_, dict) else []:
                if not bomb_em and isinstance(w, dict) and w.get("trigger") == "bombs" and w.get("external") \
                        and isinstance(w.get("emitter"), str):
                    bomb_em = w["emitter"]
        out[s["index"]] = (pos, bomb_em)
    return out


def _weapon_lines(trigger: str, blk: str, emitter: str, bullets: int | None, ind: str = "", separate: bool = False) -> list[str]:
    lines = ["Weapon{", f'  trigger:t="{trigger}"', f'  blk:t="{blk}"', f'  emitter:t="{emitter}"']
    if bullets:
        lines.append(f"  bullets:i={bullets}")
    lines.append("  external:b=yes")
    if separate:  # as the game's own pylon presets: one pylon at a time, not every pylon with that trigger at once
        lines.append("  separate:b=yes")
    lines.append("}")
    return [ind + s for s in lines]


# Pylon weapons, modified ({"w": key, "n": count, "mod": {...}}): the weapon file's payload block by folder,
# and what each "mod" key overrides there (absolute values; "g" / "gReq" only on guided weapons: overload limit,
# autopilot; "kt": a nuclear charge). The page sends only the values the weapon has (server.weapon_base).
PAYLOADS = {"rocketguns": "rocket", "bombguns": "bomb", "torpedoes": "torpedo", "mines": "mine"}
WEAPON_MODS = {
    "e": ("explosiveMass", 0, 1_000_000),  # kg of explosive
    "mass": ("mass", 0.1, 1_000_000),      # kg, the whole weapon
    "force": ("force", 0, 10_000_000),     # N, rocket motor thrust
    "burn": ("timeFire", 0, 600),          # s, rocket motor burn time
    "mach": ("machMax", 0.1, 50),
    "fins": ("finsLatAccel", 0, 1000),     # lateral acceleration the fins can give
    "range": ("maxDistance", 0, 1_000_000),  # m
}
# The explosion the game shows follows the weapon, not its explosive: the one of the game's weapons of that size
# (datamine, explosive mass in kg up to which each effect is used). Bombs: explosionFx; missiles / rockets:
# explosionEffect, and past their biggest, a bomb's explosionFx as well.
BOMB_FX = ((20, "bomb_expl_50kg"), (50, "bomb_expl_100kg"), (130, "bomb_expl_200kg"), (460, "bomb_expl_500kg"),
           (900, "bomb_expl_1000kg"), (float("inf"), "bomb_expl_5000kg"))
ROCKET_FX = ((2, "explosion_midair_rocket_tiny"), (25, "explosion_midair_rocket_small"),
             (100, "explosion_midair_rocket_medium"), (float("inf"), "explosion_midair_rocket_big"))


def _fx(table, kg: float) -> str:
    return next(fx for limit, fx in table if kg <= limit)


# Advanced changes (mod["adv"] = {"rocket/guidance/workTime": {"t": "r", "v": 30}}): any value of the weapon file,
# by its path and type as the datamine shows it (server.weapon_base "tree"). Checked here: names, types, ranges.
ADV_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,63}$")
ADV_TEXT = re.compile(r"^[A-Za-z0-9_\-./ ]{0,120}$")
ADV_MAX = 500


def _adv_value(t: str, v):
    """A checked advanced value, or CdkError."""
    import math
    def real(x):
        x = float(x)
        if not math.isfinite(x) or abs(x) > 1e9:
            raise ValueError
        return x
    try:
        if t == "r":
            return real(v)
        if t == "i":
            x = int(v)
            if abs(x) > 2_000_000_000:
                raise ValueError
            return x
        if t == "b":
            if not isinstance(v, bool):
                raise ValueError
            return v
        if t == "t":
            if not isinstance(v, str) or not ADV_TEXT.match(v):
                raise ValueError
            return v
        if t in ("p2", "p3", "p4"):
            if not isinstance(v, list) or len(v) != int(t[1]):
                raise ValueError
            return [real(x) for x in v]
    except (TypeError, ValueError):
        pass
    raise CdkError(f"Invalid advanced value ({t})")


def _custom_weapon(w: dict, mod, what: str) -> str | None:
    """The text of a modified copy of catalog weapon w (include + overrides), None when nothing changes.
    Launchers (containers) hold their weapon in a file of their own: not handled yet."""
    if not isinstance(mod, dict) or w.get("pod"):
        return None
    folder = str(w.get("p", "")).replace("\\", "/").split("/")[-2].lower()
    payload = PAYLOADS.get(folder)
    if not payload:
        return None
    tree: dict[tuple, tuple] = {}  # (block, ..., name) -> (type, value); "+" types: a new value, not an override
    for key, (field, lo, hi) in WEAPON_MODS.items():
        v = _num(mod, key, lo, hi)
        if v is not None:
            tree[(payload, field)] = ("r", v)
    e = _num(mod, "e", 0, 1_000_000)
    if e is not None and payload == "bomb":
        tree[(payload, "explosionFx")] = ("t", _fx(BOMB_FX, e))
    elif e is not None and payload == "rocket":
        tree[(payload, "explosionEffect")] = ("t", _fx(ROCKET_FX, e))
        if e > 220:  # bigger than any missile: a bomb's explosion too (a new value in that block, not an override)
            tree[(payload, "explosionFx")] = ("+t", _fx(BOMB_FX, e))
    kt = _num(mod, "kt", 0.001, 100_000)
    if kt is not None and payload in ("bomb", "rocket"):
        # a nuclear charge, as the game's nuclear bombs (yield in kilotons); new values in that block, unless it is one
        if w.get("c") == "nuke":
            tree[(payload, "yield")] = ("r", kt)
        else:
            tree[(payload, "yield")] = ("+r", kt)
            tree[(payload, "splashFallBySquare")] = ("+b", True)
            if kt < 15:  # the 5 kt bombs name their explosion; the bigger ones leave the game's own
                tree[(payload, "nuclearExplosionFx")] = ("+t", "explosion_massive")
    if payload == "rocket" and w.get("g"):
        g = _num(mod, "g", 1, 1000)
        if g is not None:
            tree[(payload, "loadFactorMax")] = ("r", g)  # the missile's overload limit
        g_req = _num(mod, "gReq", 1, 1000)
        if g_req is not None:  # what its autopilot asks for at most (both raised: 100 G turns, checked in game)
            tree[(payload, "guidance", "guidanceAutopilot", "reqAccelMax")] = ("r", g_req)
    adv = mod.get("adv")
    if isinstance(adv, dict):
        if len(adv) > ADV_MAX:
            raise CdkError("Too many advanced changes")
        for path, tv in adv.items():
            parts = tuple(str(path).split("/"))
            if not 1 <= len(parts) <= 8 or not all(ADV_KEY.match(x) for x in parts) or not isinstance(tv, dict):
                raise CdkError("Invalid advanced value")
            t = str(tv.get("t"))
            tree[parts] = (t, _adv_value(t, tv.get("v")))  # wins over the simple fields
    if not tree:
        return None
    b = _header(what, w["p"])
    _write_tree(b, tree)
    return str(b)


HP_MULT = 1000.0
# "Unbreakable airframe": the flight model's breaking limits, raised (speeds km/h IAS, overloads in newtons)
NO_BREAK_SPEED = 100000.0
_BREAK_SPEEDS = {"Vne", "VNE", "VneHeli", "VneCockpitDoor", "CockpitOpenedDoorBreakSpeed", "GearDestructionIndSpeed",
                 "AirbrakeDestructionIndSpeed", "chuteRipSpeed"}
_BREAK_MACHS = {"VneMach", "MNE"}  # MNE: each wing's Mach limit (Strength), 0.96 on the F-14B (checked in game)
_BREAK_OVERLOADS = {"CritOverload", "WingCritOverload"}


def _structural_overrides(node, path=()) -> dict:
    """{path: (type, value)} raising every breaking limit of a flight model: wings torn off by speed or g
    (Vne / VneMach / Strength VNE and MNE, CritOverload / WingCritOverload), gear, flaps, airbrake, canopy, chute."""
    out = {}
    if not isinstance(node, dict):
        return out
    for k, v in node.items():
        p = path + (k,)
        if isinstance(v, dict):
            out.update(_structural_overrides(v, p))
        elif isinstance(v, bool):
            continue
        elif k in _BREAK_SPEEDS and isinstance(v, (int, float)) and v > 0:
            out[p] = ("r", NO_BREAK_SPEED)
        elif k in _BREAK_MACHS and isinstance(v, (int, float)):
            out[p] = ("r", 100.0)
        elif k in _BREAK_OVERLOADS and isinstance(v, list) and len(v) == 2 and all(isinstance(x, (int, float)) for x in v):
            out[p] = ("p2", [float(v[0]) * 100.0, float(v[1]) * 100.0])
        elif k.startswith("FlapsDestructionIndSpeed") and isinstance(v, list) and len(v) == 2:
            out[p] = ("p2", [float(v[0]), NO_BREAK_SPEED])
    return out


def _power_overrides(fm: dict, mul: float) -> dict:
    """{path: (type, value)} multiplying an aircraft's engine output: jets their thrust table base (ThrustMax0),
    piston engines their power (Main/Power and the compressor's Power<n> / PowerConstRPM<n> / PowerAtCeiling<n>)."""
    out = {}
    for ek, e in (fm or {}).items():
        if not (ek.startswith("Engine") and isinstance(e, dict) and isinstance(e.get("Main"), dict)):
            continue
        main = e["Main"]
        base = (main.get("ThrustMax") or {}).get("ThrustMax0") if isinstance(main.get("ThrustMax"), dict) else None
        if main.get("Type") == "Jet":
            if isinstance(base, (int, float)) and base > 0:
                out[(ek, "Main", "ThrustMax", "ThrustMax0")] = ("r", float(base) * mul)
            continue
        if isinstance(main.get("Power"), (int, float)) and main["Power"] > 0:
            out[(ek, "Main", "Power")] = ("r", float(main["Power"]) * mul)
        comp = e.get("Compressor")
        for k, v in (comp.items() if isinstance(comp, dict) else ()):
            if re.fullmatch(r"(Power|PowerConstRPM|PowerAtCeiling)\d+", k) and isinstance(v, (int, float)) and v > 0:
                out[(ek, "Compressor", k)] = ("r", float(v) * mul)
    return out


def _handling_overrides(fm: dict) -> dict:
    """{path: (type, value)} for an aircraft that turns, rolls and pitches far better (super mobility): moment of
    inertia x0.4, control surfaces x1.5 in area, x2 in deflection rate and in the speed up to which they stay
    effective, the wing's maximum lift x1.3 (old flight models: NoFlaps / FullFlaps; recent: WingPlane* /
    FlapsPolar*), every minimum drag coefficient (CdMin) x0.5."""
    out = {}

    def num(v):
        return isinstance(v, (int, float)) and not isinstance(v, bool)

    def scaled(v, k):
        if num(v):
            return ("r", float(v) * k)
        if isinstance(v, list) and len(v) in (2, 3) and all(num(x) for x in v):
            return ("p2" if len(v) == 2 else "p3", [float(x) * k for x in v])
        return None

    def walk(n, path):
        for k, v in n.items():
            p = path + (k,)
            if isinstance(v, dict):
                walk(v, p)
                continue
            mul = None
            if p == ("MomentOfInertia",):
                mul = 0.4
            elif len(p) == 1 and k in ("AileronEffectiveSpeed", "RudderEffectiveSpeed", "ElevatorsEffectiveSpeed",
                                       "AileronMaxDv", "ElevatorMaxDv", "RudderMaxDv"):
                mul = 2.0
            elif len(p) >= 2 and p[-2] == "Areas" and k in ("Aileron", "Elevator", "Rudder"):
                mul = 1.5
            elif p[0] == "Aerodynamics" and k == "CdMin":
                mul = 0.5
            elif p[0] == "Aerodynamics" and k in ("ClCritHigh", "ClCritLow") and (
                    any(x in ("NoFlaps", "FullFlaps") for x in p)
                    or (any(x.startswith("WingPlane") for x in p) and any(x.startswith("FlapsPolar") for x in p))):
                mul = 1.3
            got = scaled(v, mul) if mul else None
            if got:
                out[p] = got

    walk(fm or {}, ())
    return out


def _write_tree(b: "Blk", tree: dict):
    """Writes {path: (type, value)} as nested @override blocks ("+<type>": a new value, written as is)."""
    groups: dict = {}
    for path, tv in tree.items():
        if len(path) == 1:
            typ, v = tv
            if typ.startswith("+"):
                b.line(f"{path[0]}:{typ[1:]}={_blk_value(typ[1:], v)}")
            else:
                b.line(f'"@override:{path[0]}":{typ}={_blk_value(typ, v)}')
        else:
            groups.setdefault(path[0], {})[path[1:]] = tv
    for name, sub in groups.items():
        b.open(name)
        _write_tree(b, sub)
        b.close()


def _has_hp(node) -> bool:
    if isinstance(node, dict):
        return any(k == "hp" or _has_hp(v) for k, v in node.items())
    return False


def _damage_overrides(b: "Blk", node: dict, mult: float):
    """Multiplies every hit-point value of the damage model (DamageParts)."""
    for k, v in node.items():
        if k == "hp" and isinstance(v, (int, float)) and not isinstance(v, bool):
            if isinstance(v, int):
                b.int("hp", min(int(v * mult), 2_000_000_000))
            else:
                b.real("hp", v * mult)
        elif isinstance(v, dict) and _has_hp(v):
            b.open(k)
            _damage_overrides(b, v, mult)
            b.close()


def build_files(vid: str, cat: str, details: dict, mods: dict, host: str, pylons: dict | None,
                air_method: str = "custom", unit_data: dict | None = None,
                catalog: dict | None = None, tag: str = "", fm_data: dict | None = None) -> tuple[dict[str, str], str, str, str]:
    """Returns ({path under the package: text}, weapons preset or "", mission unit_class, package dir).
    tag: names the files and the unit after it instead of the vehicle id (AI units: "<id>_ai1"…).
    fm_data: the aircraft's flight model (datamine), for mods["noStructural"] (unbreakable airframe)."""
    flyer = cat in ("air", "heli")
    custom_name = flyer and air_method == "custom"
    name = tag or vid
    if not SAFE.match(vid) or not SAFE.match(name) or (not custom_name and not SAFE.match(host or "")):
        raise CdkError("Invalid vehicle or host id")
    if cat not in UNIT_DIRS:
        raise CdkError("Unsupported vehicle type")
    mods = mods or {}
    st = details.get("st") or {}
    files: dict[str, str] = {}
    unit_dir = UNIT_DIRS[cat]
    if custom_name:
        unit_class = f"wtftd_{name}".lower()
        host_path = f"{unit_dir}/{unit_class}.blk"
        pkg = "pkg_user"
    else:
        unit_class = f"userVehicles/{host}"
        host_path = f"{unit_dir}/userVehicles/{host}.blk"
        pkg = "pkg_local"
    b = _header(vid, f"{unit_dir}/{vid}.blk")
    preset = ""

    if cat == "ground":
        hp = _num(mods, "hp", 1, 100000)
        rpm = _num(mods, "rpm", 100, 100000)
        mass = _num(mods, "mass", 100, 1_000_000)
        brake = _num(mods, "brake", 1, 100_000_000)
        speed_mul = _num(mods, "speedMul", 0.1, 10)
        if hp or rpm or mass or brake or speed_mul:
            b.open("VehiclePhys")
            if hp or rpm:
                b.open("engine")
                if hp:
                    b.real("horsePowers", hp)
                if rpm:
                    b.real("maxRPM", rpm)
                b.close()
            if mass:
                b.open("Mass")
                b.real("Empty", mass)
                b.real("TakeOff", mass + float(st.get("fuel", 0)))
                b.close()
            if brake or (speed_mul and st.get("gear")):
                b.open("mechanics")
                if brake:
                    b.real("maxBrakeForce", brake)
                if speed_mul and st.get("gear"):
                    b.real("mainGearRatio", float(st["gear"]) / speed_mul)
                b.close()
            b.close()

    # main gun (ground) / guns listed directly in commonWeapons
    groups = details.get("am") or []
    weapon_overrides = []
    for gi, g in enumerate(groups):
        if not g.get("wi"):
            continue
        gm = (mods.get("guns") or {}).get(str(gi)) or {}
        yaw = _num(gm, "yaw", 0.1, 1000)
        pitch = _num(gm, "pitch", 0.1, 1000)
        cap = _num(gm, "cap", 1, 100000)
        reload_s = _num(gm, "reload", 0.01, 600)
        if reload_s is None and mods.get("noReload") and g.get("sf") and g["sf"] < 20:
            reload_s = 0.05  # "No reload" cheat: near-instant reload on every gun we can reach
        shells = _clean_shells(gm.get("shells"), g)
        wfile = ""
        if (reload_s or shells) and g.get("p"):
            wname = f"{name}_w{g['wi']}".lower()
            wfile = f"gameData/Weapons/wtftd/{wname}.blk"
            wb = _header(f"{vid} weapon {g['wi']}", g["p"])
            if reload_s:
                wb.real("shotFreq", 1.0 / reload_s)
            for sid, sm in shells.items():
                if sid == "":
                    _shell_block(wb, sm)
                else:
                    wb.open(sid)
                    _shell_block(wb, sm)
                    wb.close()
            files[wfile] = str(wb)
        if yaw or pitch or cap or wfile:
            weapon_overrides.append((g["wi"], yaw, pitch, cap, wfile))
    if weapon_overrides:
        b.open("commonWeapons")
        for wi, yaw, pitch, cap, wfile in weapon_overrides:
            b.open(f"Weapon[{wi}]")
            if yaw:
                b.real("speedYaw", yaw)
            if pitch:
                b.real("speedPitch", pitch)
            if cap:
                b.int("bullets", cap)
            if wfile:
                b.text("blk", wfile)
            b.close()
        b.close()

    if cat in ("air", "heli"):
        mass = _num(mods, "mass", 10, 1_000_000)
        fuel = _num(mods, "fuel", 0, 1_000_000)
        thrust_mul = _num(mods, "thrustMul", 0.05, 20)
        tboost = _num(mods, "tboost", 0.1, 20)
        abboost = _num(mods, "abboost", 0.1, 20)
        # always wrap the flight model: the unit file now lives in userVehicles/, and a relative
        # fmFile could otherwise be looked up next to it and not be found
        if st.get("fm"):
            fm_name = f"wtftd_{name}".lower()
            fb = _header(f"{vid} flight model", f"gameData/flightModels/{st['fm']}")
            tree: dict = {}  # {path: (type, value)}, one block per section
            if mods.get("noStructural") and isinstance(fm_data, dict):
                tree.update(_structural_overrides(fm_data))
            if mods.get("superMobility") and isinstance(fm_data, dict):
                # super mobility (aircraft): handling (roll, pitch, turn, drag), engine output x3, 40 % lighter
                tree.update(_handling_overrides(fm_data))
                if not thrust_mul:
                    tree.update(_power_overrides(fm_data, 3.0))
                if not mass and st.get("mass"):
                    tree[("Mass", "EmptyMass")] = ("r", float(st["mass"]) * 0.6)
            if mass:
                tree[("Mass", "EmptyMass")] = ("r", mass)
            if fuel is not None:
                tree[("Mass", "MaxFuelMass0")] = ("r", fuel)
            if thrust_mul and st.get("thrust"):
                tree[("EngineType0", "Main", "Thrust")] = ("r", float(st["thrust"]) * thrust_mul)
            if thrust_mul and isinstance(fm_data, dict):
                # jets: the game takes the maximum thrust from the ThrustMax table (ThrustMax0 x coefficients by
                # altitude / speed), not from Main/Thrust (checked in game 2026-10-09): that base, every engine type
                for et, e in fm_data.items():
                    base = ((e.get("Main") or {}).get("ThrustMax") or {}).get("ThrustMax0") if isinstance(e, dict) and et.startswith("EngineType") else None
                    if isinstance(base, (int, float)) and not isinstance(base, bool) and base > 0:
                        tree[(et, "Main", "ThrustMax", "ThrustMax0")] = ("r", float(base) * thrust_mul)
            if tboost:
                tree[("EngineType0", "Main", "ThrottleBoost")] = ("r", tboost)
            if abboost:
                tree[("EngineType0", "Main", "AfterburnerBoost")] = ("r", abboost)
            _write_tree(fb, tree)
            text = str(fb)
            # fmFile may be resolved from flightModels/ or next to the unit file: provide both
            files[f"gameData/flightModels/fm/{fm_name}.blk"] = text
            if not custom_name:
                files[f"gameData/flightModels/userVehicles/fm/{fm_name}.blk"] = text
            b.text("fmFile", f"fm/{fm_name}.blk")

        # aircraft with fixed presets only: "lp" = their attachment points (emitters), taken from those presets
        legacy = {s["i"]: s for s in details.get("lp", [])} if not details.get("sl") else {}
        emitters = {s["i"]: s.get("e") for s in details.get("sl") or details.get("lp") or []}
        chosen, extras = [], []
        variants: dict[tuple, str] = {}  # (weapon file, its changes) -> modified copy
        raw: list[tuple] = []  # aircraft without pylons: plain weapons in the loadout
        if pylons:
            slots = {str(s["i"]): {o["n"] for o in s["o"]} for s in details.get("sl") or details.get("lp") or []}
            for k, v in pylons.items():
                if isinstance(v, str) and v and str(k) in slots and v in slots[str(k)]:
                    lp = legacy.get(int(k))
                    if lp:  # the official weapons of that point, as the game's preset hangs them
                        o = next(x for x in lp["o"] if x["n"] == v)
                        raw += [(trig, blk, lp["e"], bullets) for trig, blk, bullets in o.get("r", [])
                                if SAFE.match(str(blk).replace("/", "_").replace(".", "_")) and SAFE.match(str(trig).replace(" ", "_"))]
                    else:
                        chosen.append((int(k), v))  # official option of that pylon
                elif isinstance(v, dict) and str(k).isdigit() and emitters.get(int(k)):
                    w = (catalog or {}).get(str(v.get("w", "")))
                    if w and SAFE.match(str(v.get("w"))):
                        n = max(1, min(int(v.get("n") or 1), 8))
                        custom = _custom_weapon(w, v.get("mod"), f"{vid} {v.get('w')}")
                        if custom:  # the same weapon, modified: a file of its own that the pylon uses instead
                            # one file per weapon + changes: pylons with the same one fire one after the other
                            # (different files would fire together), and named as the game's own so the game
                            # shows its name (weapons/<file name>)
                            key = (w["p"], custom.split("\n", 1)[1])  # without the header line (its time)
                            if key not in variants:
                                stem = w["p"].replace("\\", "/").rsplit("/", 1)[-1]
                                variants[key] = f"gameData/Weapons/wtftd/{name.lower()}_{len(variants) + 1}/{stem}"
                                files[variants[key]] = custom
                            w = dict(w, p=variants[key])
                        extras.append((int(k), w, emitters[int(k)], n))  # any weapon of the game on that pylon
        # Aircraft with pylons (WeaponSlots) only take "slot + preset" entries in a loadout: a bare
        # Weapon{trigger, blk, emitter} there is ignored by the game. So each non-standard weapon
        # becomes a new WeaponPreset of its pylon (added to the unit file), picked by slot + preset.
        wslots = _weapon_slots(unit_data)
        slot_weapons: dict[int, list[tuple]] = {}  # slot -> [(trigger, blk, emitter, bullets)]
        for k, w, emitter, n in extras:
            bullets = None if w.get("pod") else n
            if k in wslots:
                bomb_em = wslots[k][1] if w["t"] == "bombs" else ""
                slot_weapons.setdefault(k, []).append((w["t"], w["p"], bomb_em or emitter, bullets))
            else:
                raw.append((w["t"], w["p"], emitter, bullets))
        if chosen or slot_weapons or raw:
            if True:
                pname = f"wtftd_{name}".lower()
                pb = Blk()
                pb.line(f"{MARKER} - {vid} custom loadout")
                for idx, name in sorted(chosen) + [(k, f"wtftd_slot{k}") for k in sorted(slot_weapons)]:
                    pb.line("Weapon{")
                    pb.line(f"  slot:i={idx}")
                    pb.line(f'  preset:t="{name}"')
                    pb.line("}")
                for weapon in raw:
                    for line in _weapon_lines(*weapon):
                        pb.line(line)
                if slot_weapons:
                    b.open("WeaponSlots")
                    for k, weapons in sorted(slot_weapons.items()):
                        b.open(f"WeaponSlot[{wslots[k][0]}]")
                        b.line("WeaponPreset{")
                        b.line(f'  name:t="wtftd_slot{k}"')
                        for weapon in weapons:
                            for line in _weapon_lines(*weapon, ind="  ", separate=True):
                                b.line(line)
                        b.line("}")
                        b.close()
                    b.close()
                files[f"gameData/flightModels/weaponPresets/{pname}.blk"] = str(pb)
                b.line('"@override:weapon_presets"{')
                b.line("  preset{")
                b.line(f'    name:t="{CUSTOM_PRESET}"')
                b.line(f'    blk:t="gameData/flightModels/weaponPresets/{pname}.blk"')
                b.line("  }")
                b.line("}")
                preset = CUSTOM_PRESET

    if mods.get("invulnerable") and isinstance((unit_data or {}).get("DamageParts"), dict):
        b.open("DamageParts")
        _damage_overrides(b, unit_data["DamageParts"], HP_MULT)
        b.close()

    files[host_path] = str(b)
    return files, preset, unit_class, pkg


# --------------------------------------------------------------------------- disk

def _content(game_dir: Path) -> Path:
    return (game_dir / "content").resolve()


def _manifest_path(user_dir: Path) -> Path:
    return user_dir / "cdk_manifest.json"


def read_manifest(user_dir: Path) -> list[str]:
    try:
        data = json.loads(_manifest_path(user_dir).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    out = []
    for p in data:
        if isinstance(p, str):
            out.append(p if p.split("/", 1)[0] in PACKAGES else f"pkg_local/{p}")  # older manifests
    return out


def _safe_target(content: Path, rel: str) -> Path:
    target = (content / rel).resolve()
    if not any((content / pkg).resolve() in target.parents for pkg in PACKAGES):
        raise CdkError("Refusing to write outside content/pkg_local or content/pkg_user")
    return target


def write_files(game_dir: Path, user_dir: Path, files: dict[str, str], pkg: str = "pkg_local") -> list[str]:
    if pkg not in PACKAGES:
        raise CdkError("Invalid package")
    content = _content(game_dir)
    manifest = set(read_manifest(user_dir))
    written = []
    for rel, text in files.items():
        # the same game path in another package would shadow this one (pkg_local wins over pkg_user):
        # drop our stale copy there
        for other in PACKAGES:
            stale = f"{other}/{rel}"
            if other != pkg and stale in manifest:
                try:
                    _safe_target(content, stale).unlink()
                except (OSError, CdkError):
                    pass
                manifest.discard(stale)
        entry = f"{pkg}/{rel}"
        target = _safe_target(content, entry)
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            try:
                head = target.read_text(encoding="utf-8", errors="ignore")[:200]
            except OSError:
                head = ""
            if MARKER not in head:  # not ours (e.g. Ask3lad's file): keep a copy
                backup = user_dir / "backup" / f"{time.strftime('%Y%m%d-%H%M%S')}_{target.name}"
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(target, backup)
        target.write_text(text, encoding="utf-8")
        manifest.add(entry)
        written.append(entry)
    user_dir.mkdir(exist_ok=True)
    _manifest_path(user_dir).write_text(json.dumps(sorted(manifest), indent=1), encoding="utf-8")
    return written


def cleanup(game_dir: Path, user_dir: Path) -> int:
    """Removes every file WTFTD wrote under content/pkg_local and content/pkg_user, then empty folders."""
    content = _content(game_dir)
    removed = 0
    for entry in read_manifest(user_dir):
        try:
            target = _safe_target(content, entry)
        except CdkError:
            continue
        if target.is_file():
            try:
                target.unlink()
                removed += 1
            except OSError:
                pass
    for pkg in PACKAGES:
        root = content / pkg
        if not root.exists():
            continue
        for d in sorted((p for p in root.rglob("*") if p.is_dir()), key=lambda p: -len(p.parts)):
            try:
                d.rmdir()  # only succeeds when empty
            except OSError:
                pass
        try:
            root.rmdir()
        except OSError:
            pass
    try:
        _manifest_path(user_dir).unlink()
    except OSError:
        pass
    return removed


def status(game_dir: Path | None, user_dir: Path) -> dict:
    files = read_manifest(user_dir)
    present = sum(1 for f in files if (game_dir / "content" / f).exists()) if game_dir else 0
    return {"files": files, "present": present}
